//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.22 at 12:14:36 PM PDT 
//


package tech.oleks.atgviz.model.gsa;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tech.oleks.atgviz.model.gsa package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tech.oleks.atgviz.model.gsa
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GsaTemplate }
     * 
     */
    public GsaTemplate createGsaTemplate() {
        return new GsaTemplate();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link GsaTemplate.ItemDescriptor }
     * 
     */
    public GsaTemplate.ItemDescriptor createGsaTemplateItemDescriptor() {
        return new GsaTemplate.ItemDescriptor();
    }

    /**
     * Create an instance of {@link GsaTemplate.Header }
     * 
     */
    public GsaTemplate.Header createGsaTemplateHeader() {
        return new GsaTemplate.Header();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link Property.Option }
     * 
     */
    public Property.Option createPropertyOption() {
        return new Property.Option();
    }

    /**
     * Create an instance of {@link GsaTemplate.ItemDescriptor.Table }
     * 
     */
    public GsaTemplate.ItemDescriptor.Table createGsaTemplateItemDescriptorTable() {
        return new GsaTemplate.ItemDescriptor.Table();
    }

}
